version: '3.7'

services:

  autobahn-conditions-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 4200:80
    environment:
      - NODE_ENV=development